/home/*/agent.out {
    minsize 10M
    hourly
    compress
    copytruncate
    rotate 6
    missingok
    maxage 1
}

/home/*/agent.err {
    minsize 10M
    hourly
    compress
    copytruncate
    rotate 6
    missingok
    maxage 1
}
